Fixes a minor issue in the deployment script by validating if the user start Hercules with given hostfiles.

diff --git a/scripts/hercules b/scripts/hercules
--- a/scripts/hercules
+++ b/scripts/hercules
@@ -430,36 +430,46 @@ if [ ! -e "$HERCULES_PATH" ]; then
     echo "$HERCULES_PATH does not exist, please check the configuration file: ${FILE}"
 fi
 
-# If slurm is not use, we hope user set three hostfiles (for metadata, data and clients).
+# If slurm is not use, we hope user set hostfiles (for metadata and data, and optionally clients).
 SERVERS_HOSTFILES_OPTION=0
 if [[ "$SLURM" -eq "0" && ! "${STATUS}" = "stop" ]]; then
     if [ ! -z "${DATA_SERVER_FILE}" ]; then
         echo "Data server file - ${DATA_SERVER_FILE}"
         if [ ! -f "${DATA_SERVER_FILE}" ]; then
-            echo "Data server file ${DATA_SERVER_FILE} does not exist"
-            exit 0
+            echo "[Error] Data server file ${DATA_SERVER_FILE} does not exist"
+            exit 1
         fi
-        # HOSTFILES_OPTION=1
         SERVERS_HOSTFILES_OPTION=$(($SERVERS_HOSTFILES_OPTION + 1))
+    elif [ ! -z "${HERCULES_DATA_HOSTFILE}" ] && [ -f "${HERCULES_DATA_HOSTFILE}" ]; then
+        echo "Data server file (from config) - ${HERCULES_DATA_HOSTFILE}"
+        SERVERS_HOSTFILES_OPTION=$(($SERVERS_HOSTFILES_OPTION + 1))
+    else
+        echo "[Error] Data server hostfile not specified or does not exist. Please set one using -d <filename> flag or configure DATA_HOSTFILE in configuration file: ${FILE}"
+        exit 1
     fi
+
     if [ ! -z "$META_SERVER_FILE" ]; then
         echo "Meta server file - $META_SERVER_FILE"
         if [ ! -f "$META_SERVER_FILE" ]; then
-            echo "Meta server file " $META_SERVER_FILE " does not exist"
-            exit 0
+            echo "[Error] Meta server file $META_SERVER_FILE does not exist"
+            exit 1
         fi
-        # SERVERS_HOSTFILES_OPTION=1
         SERVERS_HOSTFILES_OPTION=$(($SERVERS_HOSTFILES_OPTION + 1))
+    elif [ ! -z "${HERCULES_METADATA_HOSTFILE}" ] && [ -f "${HERCULES_METADATA_HOSTFILE}" ]; then
+        echo "Meta server file (from config) - ${HERCULES_METADATA_HOSTFILE}"
+        SERVERS_HOSTFILES_OPTION=$(($SERVERS_HOSTFILES_OPTION + 1))
+    else
+        echo "[Error] Metadata server hostfile not specified or does not exist. Please set one using -m <filename> flag or configure METADATA_HOSTFILE in configuration file: ${FILE}"
+        exit 1
     fi
+
     # client hostfile is optional.
     if [ ! -z "$HERCULES_MPI_HOSTFILE_NAME" ]; then
         echo "Client file - $HERCULES_MPI_HOSTFILE_NAME"
         if [ ! -f "$HERCULES_MPI_HOSTFILE_NAME" ]; then
-            echo "Client deployment file " $HERCULES_MPI_HOSTFILE_NAME " does not exist"
-            exit 0
+            echo "[Error] Client deployment file $HERCULES_MPI_HOSTFILE_NAME does not exist"
+            exit 1
         fi
-        # SERVERS_HOSTFILES_OPTION=1
-        #SERVERS_HOSTFILES_OPTION=$(($SERVERS_HOSTFILES_OPTION + 1))
     fi
 fi
 
@@ -786,7 +796,7 @@ fi
 if [[ "${VERBOSE}" -eq "1" ]]; then
     echo "SERVERS_HOSTFILES_OPTION=$SERVERS_HOSTFILES_OPTION"
 fi
-if [[ $SERVERS_HOSTFILES_OPTION -eq "0" ]]; then
+if [[ $SERVERS_HOSTFILES_OPTION -eq "0" && "$SLURM" -eq "1" ]]; then
     scontrol show hostnames "${SLURM_JOB_NODELIST}" > "${FULL_HOSTFILE}"
     # scontrol show hostnames "$SLURM_JOB_NODELIST"
 fi
@@ -822,9 +832,9 @@ then
     if [[ "${SLURM}" -eq "0" ]]; then
         ## If the path specified on the configuration file does not exist 
         ## there is an error.
-        if [[ -z "${HERCULES_METADATA_HOSTFILE}" ]];
+        if [[ -z "${HERCULES_METADATA_HOSTFILE}" || ! -f "${HERCULES_METADATA_HOSTFILE}" ]];
         then
-            echo "[Error] Metadata server file not specified, please set one using -m <filename> flag."
+            echo "[Error] Metadata server file not specified or does not exist, please set one using -m <filename> flag or configure METADATA_HOSTFILE in configuration file: ${FILE}"
             exit 1
         fi
 
@@ -873,6 +883,11 @@ else
     ## contains the hostnames of the nodes that will be used to deploy the
     ## determinate set of metadata servers.
     echo "[+] Reading metadata server file - $META_SERVER_FILE"
+    if [[ ! -f "$META_SERVER_FILE" ]]; then
+        echo "[Error] Metadata server file $META_SERVER_FILE does not exist."
+        exit 1
+    fi
+    HERCULES_METADATA_HOSTFILE="${META_SERVER_FILE}"
     readarray -t meta_hosts < "$META_SERVER_FILE"
 fi
 
@@ -931,14 +946,14 @@ fi
 ## To run the data servers.
 if [[ -z "${DATA_SERVER_FILE}" ]];
 then
-    ## If slurm is not being used and no metadata hostfile was defined
+    ## If slurm is not being used and no data hostfile was defined
     ## we checked the configuration file path.
     if [[ "$SLURM" -eq "0" ]]; then
         ## If the path specified on the configuration file does not exist 
         ## there is an error.
-        if [[ -z "${HERCULES_DATA_HOSTFILE}" ]];
+        if [[ -z "${HERCULES_DATA_HOSTFILE}" || ! -f "${HERCULES_DATA_HOSTFILE}" ]];
         then
-            echo "[Error] Data server file not specified, please set one using -d <filename> flag."
+            echo "[Error] Data server file not specified or does not exist, please set one using -d <filename> flag or configure DATA_HOSTFILE in configuration file: ${FILE}"
             exit 1
         fi
     else
@@ -959,7 +974,12 @@ else
     ## If a data file was defined we read it to create an array which
     ## contains the hostnames of the nodes that will be used to deploy the
     ## determinate set of data servers.
-    echo "[+] Reading data server file."
+    echo "[+] Reading data server file - ${DATA_SERVER_FILE}"
+    if [[ ! -f "${DATA_SERVER_FILE}" ]]; then
+        echo "[Error] Data server file ${DATA_SERVER_FILE} does not exist."
+        exit 1
+    fi
+    HERCULES_DATA_HOSTFILE="${DATA_SERVER_FILE}"
     readarray -t data_hosts < "${DATA_SERVER_FILE}"
 fi
 
