Includes support for HERCULES_BUILD_TYPE variable, allowing choosing different build paths.

diff --git a/scripts/hercules b/scripts/hercules
--- a/scripts/hercules
+++ b/scripts/hercules
@@ -418,7 +418,7 @@ if [ -z "${FILE}" ]; then
     HERCULES_PATH=$(dirname `pwd`)
 else
     ## get the project path from the configuration file.
-    HERCULES_PATH=$(cat "${FILE}" | grep "HERCULES_PATH" | awk '{print $3}')
+    HERCULES_PATH=$(grep "^[[:space:]]*HERCULES_PATH[[:space:]]*=" "${FILE}" | awk '{print $3}')
 fi
 
 if [ ! -e "$HERCULES_PATH" ]; then
@@ -458,33 +458,7 @@ if [[ "$SLURM" -eq "0" && ! "${STATUS}" = "stop" ]]; then
     fi
 fi
 
-
-## The next line returns 1 if hercules has been loaded by using spack, 0 in other case.
-IS_SPACK=$([ -z $(whereis '\<hercules\>' | awk '{print $2}') ] && echo 0 || echo 1)
-#echo "IS_SPACK=$IS_SPACK"
-# Paths may vary between spack and git.
-if [[ "$IS_SPACK" -eq "1" ]]; then
-    if [[ "${VERBOSE}" -eq "1" ]]; then
-        echo "Hercules has been loaded with Spack"
-    fi
-    # following line does not work for all spack versions.
-    #HERCULES_PATH=$(spack find --paths --loaded hercules | grep hercules | awk '{print $2}') 
-    HERCULES_BUILD_PATH=$HERCULES_PATH/bin
-    HERCULES_BASH_PATH=$HERCULES_PATH/bin
-    HERCULES_POSIX_PRELOAD="$HERCULES_PATH/lib/libhercules_posix.so"
-else
-    HERCULES_BUILD_PATH=$HERCULES_PATH/build
-    HERCULES_BASH_PATH=$HERCULES_PATH/scripts
-    HERCULES_POSIX_PRELOAD="$HERCULES_PATH/build/tools/libhercules_posix.so"
-    HERCULES_LIB_PATH=$HERCULES_PATH/install/lib
-fi
-
-export HERCULES_PATH=$HERCULES_PATH
-export HERCULES_TEMPORAL_PATH="$HERCULES_PATH/tmp/"
-if [[ "${VERBOSE}" -eq "1" ]]; then
-    echo "Hercules path - $HERCULES_PATH"
-fi
-
+# Determine the configuration file path
 if [[ "$SLURM" -eq "1" ]]; then
     echo "[+] Slurm is active."
     # Check if SLURM_JOB_ID is defined.
@@ -493,7 +467,6 @@ if [[ "$SLURM" -eq "1" ]]; then
         exit 1
     fi
     if [[ ( "${STATUS}" = "start" || "${STATUS}" = "add" ) ]]; then
-
         ## If slurm is enabled, we concat the job id to the configuration file to create a new one.
         CURR_HERCULES_CONF_FILE="${FILE}_${SLURM_JOB_ID}"
         # Copy if the file does not exist.
@@ -506,23 +479,73 @@ else
     CURR_HERCULES_CONF_FILE="${FILE}"
 fi
 
-## Read configuration file.
-export HERCULES_MOUNT_POINT=$(cat "${CURR_HERCULES_CONF_FILE}" | grep "\<MOUNT_POINT\>" | head -1 | awk '{print $3}')
-META_PORT=$(cat "${CURR_HERCULES_CONF_FILE}" | grep "\<METADATA_PORT\>" | awk '{print $3}')
-DATA_PORT=$(cat "${CURR_HERCULES_CONF_FILE}" | grep "\<DATA_PORT\>" | awk '{print $3}')
-MALLEABILITY=$(cat "${CURR_HERCULES_CONF_FILE}" | grep "\<MALLEABILITY\>" | awk '{print $3}')
-export HERCULES_NUM_METADATA=$(cat "${CURR_HERCULES_CONF_FILE}" | grep "\<NUM_META_SERVERS\>" | awk '{print $3}')
-export HERCULES_NUM_DATA=$(cat "${CURR_HERCULES_CONF_FILE}" | grep "\<NUM_DATA_SERVERS\>" | awk '{print $3}')
-NUM_NODES_FOR_CLIENTS=$(cat "${CURR_HERCULES_CONF_FILE}" | grep "\<NUM_NODES_FOR_CLIENTS\>" | awk '{print $3}')
-NUM_CLIENTS_PER_NODE=$(cat "${CURR_HERCULES_CONF_FILE}" | grep "\<NUM_CLIENTS_PER_NODE\>" | awk '{print $3}')
-ATTACHED=$(cat "${CURR_HERCULES_CONF_FILE}" | grep "\<ATTACHED\>" | awk '{print $3}')
-HERCULES_BLOCK_SIZE=$(cat "${CURR_HERCULES_CONF_FILE}" | grep "\<BLOCK_SIZE\>" | awk '{print $3}')
-STORAGE_SIZE=$(cat "${CURR_HERCULES_CONF_FILE}" | grep "\<STORAGE_SIZE\>" | awk '{print $3}')
-HERCULES_DATA_HOSTFILE=$(grep "^DATA_HOSTFILE[[:space:]]*=" "${CURR_HERCULES_CONF_FILE}" | awk '{print $3}')
-HERCULES_ALLOC_DATA_HOSTFILE=$(grep "^ALLOC_DATA_HOSTFILE[[:space:]]*=" "${CURR_HERCULES_CONF_FILE}" | awk '{print $3}')
-HERCULES_METADATA_HOSTFILE=$(cat "${CURR_HERCULES_CONF_FILE}" | grep "\<METADATA_HOSTFILE\>" | awk '{print $3}')
-INIT_HERCULES_NUM_DATA=$(cat "${CURR_HERCULES_CONF_FILE}" | grep "\<INIT_NUM_DATA_SERVERS\>" | awk '{print $3}')
-UPPER_BOUND_MALLEABILITY=$(cat "${CURR_HERCULES_CONF_FILE}" | grep "\<UPPER_BOUND_MALLEABILITY\>" | awk '{print $3}')
+# Try to get HERCULES_BUILD_TYPE from the config file.
+# If found, it will overwrite the environment variable. If not, the environment variable is kept.
+if [[ -f "${CURR_HERCULES_CONF_FILE}" ]]; then
+    CONF_BUILD_TYPE=$(grep "^[[:space:]]*HERCULES_BUILD_TYPE[[:space:]]*=" "${CURR_HERCULES_CONF_FILE}" | awk '{print $3}')
+    if [[ -n "${CONF_BUILD_TYPE}" ]]; then
+        HERCULES_BUILD_TYPE="${CONF_BUILD_TYPE}"
+    fi
+fi
+
+# Get the build path (where is HERCULES installed).
+## The next line returns 1 if hercules has been loaded by using spack, 0 in other case.
+IS_SPACK=$([ -z $(whereis '\<hercules\>' | awk '{print $2}') ] && echo 0 || echo 1)
+#echo "IS_SPACK=$IS_SPACK"
+
+# Paths may vary between spack and git.
+if [[ "$IS_SPACK" -eq "1" ]]; then
+    if [[ "${VERBOSE}" -eq "1" ]]; then
+        echo "Hercules has been loaded with Spack"
+    fi
+    # next line does not work for all spack versions.
+    #HERCULES_PATH=$(spack find --paths --loaded hercules | grep hercules | awk '{print $2}') 
+    HERCULES_BUILD_PATH=$HERCULES_PATH/bin
+    HERCULES_BASH_PATH=$HERCULES_PATH/bin
+    HERCULES_POSIX_PRELOAD="$HERCULES_PATH/lib/libhercules_posix.so"
+else
+    # Check if HERCULES_BUILD_TYPE is set (either from config file or environment)
+    if [ -n "${HERCULES_BUILD_TYPE}" ]; then
+        HERCULES_BUILD_PATH="${HERCULES_PATH}/build-${HERCULES_BUILD_TYPE}"
+    else
+        HERCULES_BUILD_PATH="${HERCULES_PATH}/build"
+    fi
+
+    # Verify if the constructed build path actually exists
+    if [ ! -d "${HERCULES_BUILD_PATH}" ]; then
+        echo "Error: Build directory '${HERCULES_BUILD_PATH}' does not exist." >&2
+        exit 1
+    fi
+    
+    HERCULES_BASH_PATH="${HERCULES_PATH}/scripts"
+    HERCULES_POSIX_PRELOAD="${HERCULES_BUILD_PATH}/tools/libhercules_posix.so"
+    HERCULES_LIB_PATH="${HERCULES_PATH}/install/lib"
+fi
+
+export HERCULES_PATH=$HERCULES_PATH
+export HERCULES_TEMPORAL_PATH="$HERCULES_PATH/tmp/"
+
+if [[ "${VERBOSE}" -eq "1" ]]; then
+    echo "Hercules path - $HERCULES_PATH"
+fi
+
+# Read the rest of the configuration file variables
+export HERCULES_MOUNT_POINT=$(grep "^[[:space:]]*MOUNT_POINT[[:space:]]*=" "${CURR_HERCULES_CONF_FILE}" | head -1 | awk '{print $3}')
+META_PORT=$(grep "^[[:space:]]*METADATA_PORT[[:space:]]*=" "${CURR_HERCULES_CONF_FILE}" | awk '{print $3}')
+DATA_PORT=$(grep "^[[:space:]]*DATA_PORT[[:space:]]*=" "${CURR_HERCULES_CONF_FILE}" | awk '{print $3}')
+MALLEABILITY=$(grep "^[[:space:]]*MALLEABILITY[[:space:]]*=" "${CURR_HERCULES_CONF_FILE}" | awk '{print $3}')
+export HERCULES_NUM_METADATA=$(grep "^[[:space:]]*NUM_META_SERVERS[[:space:]]*=" "${CURR_HERCULES_CONF_FILE}" | awk '{print $3}')
+export HERCULES_NUM_DATA=$(grep "^[[:space:]]*NUM_DATA_SERVERS[[:space:]]*=" "${CURR_HERCULES_CONF_FILE}" | awk '{print $3}')
+NUM_NODES_FOR_CLIENTS=$(grep "^[[:space:]]*NUM_NODES_FOR_CLIENTS[[:space:]]*=" "${CURR_HERCULES_CONF_FILE}" | awk '{print $3}')
+NUM_CLIENTS_PER_NODE=$(grep "^[[:space:]]*NUM_CLIENTS_PER_NODE[[:space:]]*=" "${CURR_HERCULES_CONF_FILE}" | awk '{print $3}')
+ATTACHED=$(grep "^[[:space:]]*ATTACHED[[:space:]]*=" "${CURR_HERCULES_CONF_FILE}" | awk '{print $3}')
+HERCULES_BLOCK_SIZE=$(grep "^[[:space:]]*BLOCK_SIZE[[:space:]]*=" "${CURR_HERCULES_CONF_FILE}" | awk '{print $3}')
+STORAGE_SIZE=$(grep "^[[:space:]]*STORAGE_SIZE[[:space:]]*=" "${CURR_HERCULES_CONF_FILE}" | awk '{print $3}')
+HERCULES_DATA_HOSTFILE=$(grep "^[[:space:]]*DATA_HOSTFILE[[:space:]]*=" "${CURR_HERCULES_CONF_FILE}" | awk '{print $3}')
+HERCULES_ALLOC_DATA_HOSTFILE=$(grep "^[[:space:]]*ALLOC_DATA_HOSTFILE[[:space:]]*=" "${CURR_HERCULES_CONF_FILE}" | awk '{print $3}')
+HERCULES_METADATA_HOSTFILE=$(grep "^[[:space:]]*METADATA_HOSTFILE[[:space:]]*=" "${CURR_HERCULES_CONF_FILE}" | awk '{print $3}')
+INIT_HERCULES_NUM_DATA=$(grep "^[[:space:]]*INIT_NUM_DATA_SERVERS[[:space:]]*=" "${CURR_HERCULES_CONF_FILE}" | awk '{print $3}')
+UPPER_BOUND_MALLEABILITY=$(grep "^[[:space:]]*UPPER_BOUND_MALLEABILITY[[:space:]]*=" "${CURR_HERCULES_CONF_FILE}" | awk '{print $3}')
 
 if [ -z "$INIT_HERCULES_NUM_DATA" ] || [ "$INIT_HERCULES_NUM_DATA" = "0" ] ; then
     INIT_HERCULES_NUM_DATA=$HERCULES_NUM_DATA
